/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eclipsemarkets.pbc.pricer.sim;

import com.eclipsemarkets.data.PointBoxQuoteCode;
import com.eclipsemarkets.pbc.kernel.IPbcKernel;
import java.awt.BorderLayout;
import javax.swing.JTable;

/**
 *
 * @author Zhijun Zhang
 */
public class PricingCompFrame extends AbstractPricingRuntimeCurveFrame {
    
    private PricingCompTableInputPanel topPricingCompTableInputPanel;

    public PricingCompFrame(IPbcKernel kernel, PointBoxQuoteCode targetCode) {
        super(kernel, targetCode);
        initComponents();
        
        initializeCurveFrame(jClassSelector, jGroupSelector, jCodeSelector);
    }

    @Override
    String getFrameTitle() {
        return "Comp";
    }

    @Override
    void updateFrameForTargetCodeImpl(PointBoxQuoteCode code) {
        PricingCompTableModel model = new PricingCompTableModel(this);
        jTargetTable.setModel(model);
        jTargetTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTargetTable.getTableHeader().setReorderingAllowed(false);
        model.setUpColumns(jTargetTable);
        
        if (topPricingCompTableInputPanel == null){
            topPricingCompTableInputPanel = new PricingCompTableInputPanel(model);
            jTopPanel.add(topPricingCompTableInputPanel, BorderLayout.CENTER);
        }else{
            topPricingCompTableInputPanel.setTableModel(model);
        }
    }

    @Override
    JTable getTargetTable() {
        return jTargetTable;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTopPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTargetTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jClassSelector = new javax.swing.JComboBox();
        jGroupSelector = new javax.swing.JComboBox();
        jCodeSelector = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRefresh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(120);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jTopPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTopPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setTopComponent(jTopPanel);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jTargetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTargetTable);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel4);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.add(jClassSelector);

        jPanel2.add(jGroupSelector);

        jPanel2.add(jCodeSelector);
        jPanel2.add(jLabel2);
        jPanel2.add(jLabel3);

        jRefresh.setText("Refresh");
        jRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefreshActionPerformed(evt);
            }
        });
        jPanel2.add(jRefresh);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshActionPerformed
        updateFrameForTargetCode(getTargetCode());
    }//GEN-LAST:event_jRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jClassSelector;
    private javax.swing.JComboBox jCodeSelector;
    private javax.swing.JComboBox jGroupSelector;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTargetTable;
    private javax.swing.JPanel jTopPanel;
    // End of variables declaration//GEN-END:variables
}
