/**
 * Eclipse Market Solutions LLC
 *
 * VerticalBasePanel.java
 *
 * @author Zhijun Zhang
 * Created on May 27, 2010, 7:14:54 AM
 */

package com.eclipsemarkets.pbc.face;

import com.eclipsemarkets.pbc.kernel.PointBoxConsoleProperties;
import java.awt.BorderLayout;

/**
 *
 * @author Zhijun Zhang
 */
public class VerticalBasePanel extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    private final IPbcFace face;

    public static VerticalBasePanel createVerticalBasePanel(final IPbcFace face){
        return new VerticalBasePanel(face);
    }
    
    /** Creates new form VerticalBasePanel
     * @param face
     */
    private VerticalBasePanel(final IPbcFace face) {
        initComponents();
        this.face = face;
        initializeTalker();
        initializeViewer();
        
        setupSpliterLocationDuringInitialization();
    }

    private void initializeTalker() {
        jBuddyListZone.add(face.getBuddyListBasePanel(), BorderLayout.CENTER);
        jMessagingZone.add(face.getMessagingBasePanel(), BorderLayout.CENTER);
    }

    private void initializeViewer() {
        this.jViewerZone.add(face.getViewerBasePanel(), BorderLayout.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPrimarySplitPane = new javax.swing.JSplitPane();
        jSecondarySplitPane = new javax.swing.JSplitPane();
        jViewerZone = new javax.swing.JPanel();
        jMessagingZone = new javax.swing.JPanel();
        jBuddyListZone = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(796, 541));
        setPreferredSize(new java.awt.Dimension(796, 541));
        setLayout(new java.awt.BorderLayout());

        jPrimarySplitPane.setDividerLocation(500);
        jPrimarySplitPane.setResizeWeight(1.0);
        jPrimarySplitPane.setName("jPrimarySplitPane"); // NOI18N
        jPrimarySplitPane.setOneTouchExpandable(true);

        jSecondarySplitPane.setDividerLocation(250);
        jSecondarySplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSecondarySplitPane.setResizeWeight(1.0);
        jSecondarySplitPane.setName("jSecondarySplitPane"); // NOI18N
        jSecondarySplitPane.setOneTouchExpandable(true);

        jViewerZone.setName("jViewerZone"); // NOI18N
        jViewerZone.setLayout(new java.awt.BorderLayout());
        jSecondarySplitPane.setTopComponent(jViewerZone);

        jMessagingZone.setMinimumSize(new java.awt.Dimension(500, 300));
        jMessagingZone.setName("jMessagingZone"); // NOI18N
        jMessagingZone.setPreferredSize(new java.awt.Dimension(500, 300));
        jMessagingZone.setLayout(new java.awt.BorderLayout());
        jSecondarySplitPane.setRightComponent(jMessagingZone);

        jPrimarySplitPane.setLeftComponent(jSecondarySplitPane);

        jBuddyListZone.setMinimumSize(new java.awt.Dimension(275, 500));
        jBuddyListZone.setName("jBuddyListZone"); // NOI18N
        jBuddyListZone.setLayout(new java.awt.BorderLayout());
        jPrimarySplitPane.setRightComponent(jBuddyListZone);

        add(jPrimarySplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBuddyListZone;
    private javax.swing.JPanel jMessagingZone;
    private javax.swing.JSplitPane jPrimarySplitPane;
    private javax.swing.JSplitPane jSecondarySplitPane;
    private javax.swing.JPanel jViewerZone;
    // End of variables declaration//GEN-END:variables

    void storeDockingSpliterLocation() {
        PointBoxConsoleProperties prop=PointBoxConsoleProperties.getSingleton();
        prop.storePrimarySpliterLocation(jPrimarySplitPane.getDividerLocation());
        prop.storeSecondarySpliterLocation(jSecondarySplitPane.getDividerLocation());
    }

    void setupSpliterLocationDuringInitialization() {
        PointBoxConsoleProperties prop=PointBoxConsoleProperties.getSingleton();
        Integer primarySpliterLocation=prop.retrievePrimarySpliterLocation();
        Integer secondarySpliterLocation=prop.retrieveSecondarySpliterLocation();
        if(primarySpliterLocation!=null){
            jPrimarySplitPane.setDividerLocation(primarySpliterLocation);
        }
        if(secondarySpliterLocation!=null){
            jSecondarySplitPane.setDividerLocation(secondarySpliterLocation);
        }        
    }

}
