/**
 * Eclipse Market Solutions LLC
 */
/*
 * BuddyProfileDialog.java
 *
 * @author Zhijun Zhang
 * Created on May 16, 2010, 5:34:36 PM
 */

package com.eclipsemarkets.pbc.face.talker;

import com.eclipsemarkets.gateway.user.GatewayBuddyListFactory;
import com.eclipsemarkets.gateway.user.IGatewayConnectorBuddy;
import com.eclipsemarkets.gateway.user.PbcReservedTerms;
import com.eclipsemarkets.global.DataGlobal;
import com.eclipsemarkets.global.SwingGlobal;
import com.eclipsemarkets.pbc.runtime.settings.record.IBuddyProfileRecord;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Zhijun Zhang
 */
class BuddyProfileDialog extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;

    private String userOwner;
    private String profileUuid;
    private IGatewayConnectorBuddy buddy;
    private IBuddyListPopupMenu handler;
    private String gatewayServerType;
    private String screenName;

    private IPbcTalker talker;

    /** Creates new form BuddyProfileDialog
     * @param parent
     * @param modal
     */
    BuddyProfileDialog(IPbcTalker talker, boolean modal ) {
        super(talker.getPointBoxFrame(), modal);
        initComponents();
        this.talker = talker;
    }

    @Override
    public void setVisible(boolean value){
        if (value){
            setLocation(SwingGlobal.getCenterPointOfParentWindow(talker.getPointBoxFrame(), this));
            if (DataGlobal.isNonEmptyNullString(profileUuid)){
                ((TitledBorder)jTitlePanel.getBorder()).setTitle(profileUuid);
            }else{
                ((TitledBorder)jTitlePanel.getBorder()).setTitle("Buddy Profile: ");
            }
        }
        super.setVisible(value);
    }

    public void setBuddyProfileKeysAndLoadValues (IGatewayConnectorBuddy userOwner, IGatewayConnectorBuddy buddy, IBuddyListPopupMenu handler) {
       this.userOwner = userOwner.getIMScreenName();
       this.buddy = buddy;
       if (buddy.getLoginOwner() == null){
           this.profileUuid = buddy.getIMUniqueName();
       }else{
           this.profileUuid = buddy.getIMUniqueName() + " ("+buddy.getLoginOwner().getIMScreenName()+")";
       }
       this.gatewayServerType=buddy.getIMServerType().toString();
       this.screenName=buddy.getIMScreenName();
       this.handler = handler;
       loadValues();
    }
    
    public void loadValues () {
       resetFields ();
       IBuddyProfileRecord buddyProfile = talker.getKernel().retrieveBuddyProfileRecord(buddy);
       if (buddyProfile == null){
           return;
       }
       populateFields (buddyProfile);
       buddyProfile.cleanUp();
    }

    private void populateFields (IBuddyProfileRecord buddyProfile) {
       jFirstName.setText(buddyProfile.getFirstName());
       jLastName.setText(buddyProfile.getLastName());
       jNickName.setText(buddyProfile.getNickName());
       jNoteTextArea.setText(buddyProfile.getNotes());
       jStreet.setText(buddyProfile.getWorkStreet());

       jCity.setText(buddyProfile.getWorkCity());
       jState.setText(buddyProfile.getWorkState());
       jZip.setText(buddyProfile.getWorkZip());
       jPhone.setText(buddyProfile.getWorkPhone());
//       jMobile.setText(buddyProfile.getCellPhone());

//       jFax.setText(buddyProfile.getWorkFax());
//       jPager.setText(buddyProfile.getPager());
       jEmail.setText(buddyProfile.getWorkEmail());
    }
//    
//    private IBuddyProfileRecord retrieveFromStorage () {
//       IBuddyProfileRecord buddyProfile = talker.getKernel().getPointBoxConsoleRuntime().createBuddyProfileRecordInstance();
//       buddyProfile.setUserOwner(userOwner);
//       buddyProfile.setProfileUuid(profileUuid);
//       buddyProfile.setGatewayServerType(gatewayServerType);
//       buddyProfile.setScreenName(screenName);
//       talker.getKernel().loadBuddyProfileRecord(buddyProfile);
//       return buddyProfile;
//    }


    private void resetFields () {
       jFirstName.setText("");
       jLastName.setText("");
       jNickName.setText("");
       jNoteTextArea.setText("");
       jStreet.setText("");

       jCity.setText("");
       jState.setText("");
       jZip.setText("");
       jPhone.setText("");
      // jMobile.setText("");

       //jFax.setText("");
      // jPager.setText("");
       jEmail.setText("");
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitlePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jNickName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jNoteTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jStreet = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCity = new javax.swing.JTextField();
        jState = new javax.swing.JTextField();
        jZip = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPhone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jSave = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit personal profile:");

        jTitlePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buddy: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jTitlePanel.setName("jTitlePanel"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("First Name:");
        jLabel1.setName("jLabel1"); // NOI18N

        jFirstName.setName("jFirstName"); // NOI18N

        jLabel2.setText("Last Name:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLastName.setName("jLastName"); // NOI18N

        jLabel3.setText("Nick Name:");
        jLabel3.setName("jLabel3"); // NOI18N

        jNickName.setName("jNickName"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jNickName, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jNoteTextArea.setColumns(20);
        jNoteTextArea.setRows(5);
        jNoteTextArea.setWrapStyleWord(true);
        jNoteTextArea.setAutoscrolls(false);
        jNoteTextArea.setName("jNoteTextArea"); // NOI18N
        jScrollPane1.setViewportView(jNoteTextArea);

        jLabel4.setText("Notes:");
        jLabel4.setName("jLabel4"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel5.setText("Contact Information:");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("Street:");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText("City:");
        jLabel7.setName("jLabel7"); // NOI18N

        jStreet.setName("jStreet"); // NOI18N

        jLabel8.setText("State:");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText("Zip:");
        jLabel9.setName("jLabel9"); // NOI18N

        jCity.setName("jCity"); // NOI18N

        jState.setName("jState"); // NOI18N

        jZip.setName("jZip"); // NOI18N

        jLabel10.setText("Phone:");
        jLabel10.setName("jLabel10"); // NOI18N

        jPhone.setName("jPhone"); // NOI18N

        jLabel14.setText("Email:");
        jLabel14.setName("jLabel14"); // NOI18N

        jEmail.setName("jEmail"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jState, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jZip))
                            .addComponent(jCity, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSave.setText("Save"); // NOI18N
        jSave.setName("jSave"); // NOI18N
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        jCancel.setText("Cancel"); // NOI18N
        jCancel.setName("jCancel"); // NOI18N
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTitlePanelLayout = new javax.swing.GroupLayout(jTitlePanel);
        jTitlePanel.setLayout(jTitlePanelLayout);
        jTitlePanelLayout.setHorizontalGroup(
            jTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTitlePanelLayout.createSequentialGroup()
                .addGroup(jTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTitlePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jTitlePanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCancel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jTitlePanelLayout.setVerticalGroup(
            jTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTitlePanelLayout.createSequentialGroup()
                .addGroup(jTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jTitlePanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSave)
                            .addComponent(jCancel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jCancelActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jSaveActionPerformed
    {//GEN-HEADEREND:event_jSaveActionPerformed
       IBuddyProfileRecord buddyProfile = talker.getKernel().getPointBoxConsoleRuntime().createBuddyProfileRecordInstance();
       buddyProfile.setUserOwner(userOwner);
       buddyProfile.setProfileUuid(profileUuid);

       buddyProfile.setFirstName(jFirstName.getText());
       buddyProfile.setLastName(jLastName.getText());
       String nickName =  jNickName.getText();
       if (PbcReservedTerms.PricerBuddy.toString().equalsIgnoreCase(nickName)){
           JOptionPane.showMessageDialog(this, "Please select a different nick name. Such a nick name is reserved.");
           return;
       }
       if (buddy != null){
            if (DataGlobal.isEmptyNullString(buddy.getNickname())){
                if ((DataGlobal.isNonEmptyNullString(nickName))){
                    buddyProfile.setNickName(nickName);
                    buddy.setNickname(nickName);
                }else{
                    //do nothing
                }
            }else{
                if ((DataGlobal.isEmptyNullString(nickName))){
                    nickName = buddy.getNickname();
                    buddyProfile.setNickName(nickName);
                }else{
                    if (nickName.equalsIgnoreCase(buddy.getNickname())){
                        buddyProfile.setNickName(nickName);
                    }else{
                        if (JOptionPane.showConfirmDialog(this, 
                                "Are you sure to change " + buddy.getIMUniqueName() + "'s nick name to " + nickName + "?", 
                                "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                        {
                            buddyProfile.setNickName(nickName);
                            buddy.setNickname(nickName);
                        }else{
                            nickName = buddy.getNickname();
                        }
                        buddyProfile.setNickName(nickName);
                    }
                }
            }
       }
       buddyProfile.setNotes(jNoteTextArea.getText());
       buddyProfile.setWorkStreet(jStreet.getText());

       buddyProfile.setWorkCity(jCity.getText());
       buddyProfile.setWorkState(jState.getText());
       buddyProfile.setWorkZip(jZip.getText());
       buddyProfile.setWorkPhone(jPhone.getText());
      // buddyProfile.setCellPhone(jMobile.getText());

       //buddyProfile.setWorkFax(jFax.getText());
       buddyProfile.setScreenName(buddy.getIMScreenName());
       buddyProfile.setGatewayServerType(buddy.getIMServerType().toString());
       //buddyProfile.setPager(jPager.getText());
       buddyProfile.setWorkEmail(jEmail.getText());
         
       handler.buddyProfileUpdated(buddyProfile, buddy);
       
       talker.populateUpdatedBuddyProfile(GatewayBuddyListFactory.getLoginUserInstance(userOwner, 
                                                                                       buddy.getIMServerType()), 
                                          buddy,
                                          buddyProfile);

       buddyProfile.cleanUp();
       setVisible(false);

    }//GEN-LAST:event_jSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancel;
    private javax.swing.JTextField jCity;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jFirstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLastName;
    private javax.swing.JTextField jNickName;
    private javax.swing.JTextArea jNoteTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPhone;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jState;
    private javax.swing.JTextField jStreet;
    private javax.swing.JPanel jTitlePanel;
    private javax.swing.JTextField jZip;
    // End of variables declaration//GEN-END:variables

}
